### ISSUE TITLE
Sphere seems not to be displayed unless dual is taken

### ISSUE THREAD

**Issue by ctylim** [hugohadfield/GAonline#2]
Hello. I found a wonderful project clifford and GAOnline implementing conformal geometrics and visualizations, and it is very convenient for me, GA learner.

I tried to display spheres, but I have to take dual only for visualizing spheres. It seems that spheres should have same dimensions with planes.

Here is my implementation using clifford.
https://github.com/ctylim/geometric-algebra/blob/master/notebook/inverse_kinematics.ipynb

I still have shallow understanding in CGA and need to keep learning but I would like to contribute if I can, thank you.

**Comment by hugohadfield** [comment]
Hi @ctylim, apologies for the slow reply have been on the beach with no internet. Thus package uses the 'normal' or 'OPNS' representation for drawing objects, so a sphere is always a grade four object like a plane! I would not be opposed to adding the functionality to draw the dual versions of objects, although I think that the functions would need to be clear in the name to make that happen eg. DrawDualSphere

**Comment by hugohadfield** [comment]
I'm afraid I'm on holiday for two more weeks now so won't be able to add any functionality for a while! I would definitely encourage you to contribute :) if you submit a pull request for any features I can review them on my phone and merge them
